apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
{{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            - name: SHRTBRED_DATABASE_HOST
              value: {{ default "shrtbred-postgresql" .Values.app.shrtbredDatabaseHost | quote}}
            - name: SHRTBRED_DATABASE_PASSWORD
              value: {{ default "shrtbred" .Values.app.shrtbredDatabasePassword | quote}}
            - name: SHRTBRED_DATABASE_PORT
              value: {{ default "5432"  .Values.app.shrtbredDatabasePort | quote }}
            - name: SHRTBRED_DATABASE_USER
              value: {{ default "shrtbred" .Values.app.shrtbredDatabaseUser  | quote}}
            - name: SHRTBRED_DATABASE_NAME
              value: {{ default "shrtbred" .Values.app.shrtbredDatabaseName | quote}}
            - name: SHRTBRED_PORT
              value: {{ default "80" .Values.app.shrtbredDatabasePort | quote}}
            - name: URL_BASE
              value: {{ default "localhost:80" .Values.app.shrtbredUrlBase | quote}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
