
---
####
#
#  ruby app serving deployment
#
####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrtbred-app
  namespace: shrtbred
  labels:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: shrtbred
      app.kubernetes.io/name: shrtbred-app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: shrtbred
        app.kubernetes.io/name: shrtbred-app
    spec:
      serviceAccountName: shrtbred-app
      securityContext:
        {}
      containers:
        - name: shrtbred
          securityContext:
            {}
          image: "jdziat/shrtbred:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: SHRTBRED_DATABASE_HOST
              value: "shrtbred-postgresql"
            - name: SHRTBRED_DATABASE_PASSWORD
              value: "shrtbred"
            - name: SHRTBRED_DATABASE_PORT
              value: "5432"
            - name: SHRTBRED_DATABASE_USER
              value: "shrtbred"
            - name: SHRTBRED_DATABASE_NAME
              value: "shrtbred"
            - name: SHRTBRED_PORT
              value: "3100"
            - name: URL_BASE
              value: "shrtbred"
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
apiVersion: v1
kind: Service
metadata:
  name: shrtbred-app
  namespace: shrtbred
  labels:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: shrtbred-assets
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-app
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: shrtbred-app
  namespace: shrtbred
  labels:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shrtbred-app
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shrtbred-app
  namespace: shrtbred
  labels:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-app