
---
####
#
#  nginx asset serving deployment
#
####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shrtbred-nginx
  namespace: shrtbred
  labels:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: shrtbred
      app.kubernetes.io/name: shrtbred-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: shrtbred
        app.kubernetes.io/name: shrtbred-nginx
    spec:
      serviceAccountName: shrtbred-nginx
      containers:
        - name: shrtbred
          image: "jdziat/shrtbred-nginx:latest" # Use a stable version if this was production
          imagePullPolicy: IfNotPresent
          env:
            - name: SHRTBRED_HOST
              value: shrtbred-app
            - name: SHRTBRED_PORT
              value: "3100"
            - name: LISTEN_PORT
              value: "3000"
          ports:
            - name: shrtbred-assets
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {} # Limit to specified resources in production
---
apiVersion: v1
kind: Service
metadata:
  name: shrtbred-nginx
  namespace: shrtbred
  labels:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-nginx
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: shrtbred-assets
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-nginx
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: shrtbred-nginx
  namespace: shrtbred
  labels:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shrtbred-nginx
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shrtbred-nginx
  namespace: shrtbred
  labels:
    app.kubernetes.io/instance: shrtbred
    app.kubernetes.io/name: shrtbred-nginx